# Config to run as Home Assistant addon
name: "NanoNVR"
description: "The tiniest NVR."
version: "0.1.0"
slug: "nanonvr"
url: "https://github.com/mancontr/nanonvr"
init: false
ingress: true
panel_icon: mdi:cctv
ports:
  21821/tcp: 21821
  21822/tcp: 21822
ports_description:
  21821/tcp: "FTP Control connection port"
  21822/tcp: "FTP Data connection port"
map:
  - config:rw
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
